### ISSUE TITLE
fullScreenMode not working

### ISSUE THREAD

**Issue by raulcrash** [Wolox/react-chat-widget#76]
Hello

What you are doing is to use chat in fullscren, and that it already came, but when I am using a fullScreenMode property nothing is appearing on the screen, simply the component is not displayed.

Follow my code:

import React, { Component } from 'react';
import Conversation from '../services/conversation';
import { Widget, addResponseMessage, addLinkSnippet, addUserMessage } from 'react-chat-widget';

import 'react-chat-widget/lib/styles.css';

class App extends Component {

  constructor() {
    super();    
    this.sendMessage = this.sendMessage.bind(this);
  }
  componentDidMount() {
    this.sendMessage('')
  }
  handleNewUserMessage = (newMessage) => {
    this.sendMessage(newMessage);
  }
  render() {
    return (
      <div className="App">
        <Widget
          handleNewUserMessage={this.handleNewUserMessage}
          title="Chatbot Ragnar"
          subtitle="Tire suas dúvidas"
          senderPlaceHolder="Digite sua dúvida aqui"
                    
        />
      </div>
    );
  }
  sendMessage(text) {
    Conversation.message({
      text
    }).then(r => {
      let size = r.output.text.length;
      for (let index = 0; index < size; index++) {
        addResponseMessage(r.output.text[index]);
      }
    });
  }

}

export default App;

**Comment by anshabmk** [comment]
This issue is because of `showChat` props being `false` by default(set by initial state). This can be fixed by checking whether the fullScreenMode prop is true or false before setting showChat prop as false.

**Comment by Samuelsolano8** [comment]
Hello I need help you could be more specific as to solve the problem (Example with code)

**Comment by adantoscano** [comment]
Use toggleWidget() in componentDidMount

**Comment by Dorian30** [comment]
Hi ! `fullScreenMode` is currently working. The problem here, and the reason why it's not displaying the widget, it's that you need to use toggleWidget as adantoscano suggested inside your Widget component. 

```
componentDidMount() {
   toggleWidget();
}
```
If you don't you won't see anything because the `Launcher` or toggle chat button will be hidden as result of the `fullScreenMode` prop being set as `true`.

Why do you need to toggle the component when it renders ? because `showChat` is `false` by default and the launcher is going to be hidden.
